sdining/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from django.conf import settings
from django.views.decorators.cache import cache_page

from rest_framework.urlpatterns import format_suffix_patterns
import xadmin

from sdiningview import views as mainviews
from business import views as businessviews
from ucenter import views as ucenterviews
from ucenter import indev as indeviews
from account import views as accountviews
from operation import views as operationviews

urlpatterns = [
    url(r'^$', mainviews.IndexView.as_view(), name='index'),

    url(r'^business/(?P<pk>[0-9]+)/$', businessviews.BusinessDetailView.as_view(), name='businessdetail'),
    url(r'^business/comment/(?P<pk>[0-9]+)/$', businessviews.CommentListView.as_view(), name='businesscommentlist'),

    url(r'^operation/makeorder/$', operationviews.makeorder, name='makeorder'),
    url(r'^operation/removeorder/$', operationviews.removeorder, name='removeorder'),
    url(r'^operation/showorder/$', operationviews.ShowOrderView.as_view(), name='showorder'),

    url(r'^ucenter/$', ucenterviews.CustomerUcenterView.as_view(), name='ucenterindex'),
    url(r'^ucenter/about/$', ucenterviews.AboutmeView.as_view(), name='about'),
    url(r'^ucenter/agree/$', ucenterviews.AgreeView.as_view(), name='agree'),
    url(r'^ucenter/done/$', ucenterviews.order_is_done, name='orderdone'),
    url(r'^ucenter/cancel/$', ucenterviews.cancel_order, name='cancelorder'),
    url(r'^ucenter/collect/$', operationviews.MycollectView.as_view(), name='mycollect'),
    url(r'^ucenter/business/$', ucenterviews.BusinessUcenterView.as_view(), name='businessucenterindex'),
    url(r'^ucenter/business/done/$', ucenterviews.business_order_is_done, name='businessorderdone'),
    url(r'^ucenter/comment/(?P<opk>[0-9]+)/$', operationviews.comment, name='comment'),
    url(r'^ucenter/business/change/$', ucenterviews.changeopen, name='changestatus'),
    url(r'^ucenter/business/aord/$', ucenterviews.accept_or_deny, name='accept_or_deny'),
    url(r'^ucenter/business/complain/$', ucenterviews.ComplainView.as_view(), name='complain'),

    url(r'^mvcapi/$', mainviews.api_root, name='api_list'),
    url(r'^mvcapi/banner/$', mainviews.APIBannerListView.as_view(), name='banner_list_api'),
    url(r'^mvcapi/food/$', businessviews.APIFoodListView.as_view(), name='food_list_api'),
    url(r'^mvcapi/food/(?P<pk>[0-9]+)/$', businessviews.APIFoodDetailView.as_view(), name='food_detail_api'),
    url(r'^mvcapi/business/$', businessviews.APIBusinessListView.as_view(), name='business_list_api'),
    url(r'^mvcapi/business/(?P<pk>[0-9]+)/$', businessviews.APIBusinessDetailView.as_view(),
        name='business_detail_api'),
    url(r'^mvcapi/', include('rest_framework.urls',
                             namespace='rest_framework')),

    url(r'^admin/', include(xadmin.site.urls)),

    url(r'^media/(?P<path>.*)', serve, {"document_root": settings.MEDIA_ROOT}),

    url(r'^qq/check/$', accountviews.qq_check, name='qqcheck'),

    url(r'^account/authguide/$', accountviews.AuthGuideView.as_view(), name='authguide'),
    url(r'^account/auth/$', accountviews.AuthView.as_view(), name='auth'),
    url(r'^account/logout/$', accountviews.LogoutView.as_view(), name='logout'),

    url(r'^indev/vouchers/$', indeviews.Myvouchers.as_view(), name='myvouchers'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

utils/rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication:

    urlpatterns = [
        ...
        url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]

In Django versions older than 1.9, the urls must be namespaced as 'rest_framework',
and you should make sure your authentication settings include `SessionAuthentication`.
"""
from __future__ import unicode_literals

from django.conf.urls import url
from django.contrib.auth import views

template_name = {'template_name': 'rest_framework/login.html'}

app_name = 'rest_framework'
urlpatterns = [
    url(r'^login/$', views.login, template_name, name='login'),
    url(r'^logout/$', views.logout, template_name, name='logout'),
]

apps/business/models.py
from django.db import models
from django.core.exceptions import ValidationError

from storage.storage import ImgStorage
from account.models import User


class Business(models.Model):
    user = models.OneToOneField(User, verbose_name="账号")
    name = models.CharField(max_length=50, verbose_name="商家名称")
    position = models.IntegerField(choices=((1, "楚园食堂"), (2, "汉园食堂"), (3, "校内商家")), verbose_name="位置", db_index=True)
    floor = models.IntegerField(choices=((1, "一楼"), (2, "二楼"), (3, "竹枫斋楼下")), verbose_name="楼层")
    type = models.IntegerField(choices=((1, "餐品"), (2, "饮品")), verbose_name="商家类型", db_index=True)
    image = models.ImageField(upload_to='bimg/%Y/%m/%d', storage=ImgStorage(), blank=True, verbose_name="商家图片")
    average = models.IntegerField(default=10, verbose_name="人均消费")
    num_like = models.IntegerField(default=0, verbose_name="点赞数")
    total_rank = models.IntegerField(default=0, verbose_name="总分")
    rank = models.IntegerField(default=0, verbose_name="综合评价")

    sort_weight = models.IntegerField(default=0, verbose_name="排序权值")

    is_open = models.BooleanField(default=False, verbose_name="是否接受预约")

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.is_open:
            for item in self.foodlist.all():
                item.can_reserve = False
                item.save()
        elif self.is_open:
            for item in self.foodlist.all():
                item.can_reserve = True
                item.save()
        super(Business, self).save()

    def delete(self, using=None, keep_parents=False):
        self.image.delete()
        super(Business, self).save()

    def get_pending_order_list(self):
        pass

    def get_food_list(self):
        return self.foodlist.all()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "商家"
        verbose_name_plural = verbose_name


class Food(models.Model):
    business = models.ForeignKey(Business, related_name='foodlist', verbose_name="商家")
    name = models.CharField(max_length=20, verbose_name="商品名")
    image = models.ImageField(upload_to='fimg/%Y/%m/%d', storage=ImgStorage(), blank=True, null=True,
                              verbose_name="商品图片")
    price = models.IntegerField(verbose_name="价格")
    can_reserve = models.BooleanField(default=False, verbose_name="可否预约")

    def clean(self):
        if self.can_reserve:
            if not self.business.is_open:
                raise ValidationError({'can_reserve': "此食物所属商家目前不接受预约"})

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "食物"
        verbose_name_plural = verbose_name


class Special(models.Model):
    business = models.OneToOneField(Business, verbose_name="商家", related_name='special')
    foods = models.ManyToManyField(Food, verbose_name="食物")

    def __str__(self):
        return self.business.name

    class Meta:
        verbose_name = "特色菜"
        verbose_name_plural = verbose_name


class Authapply(models.Model):
    user = models.OneToOneField(User, verbose_name="申请者")
    name = models.CharField(max_length=100, verbose_name="商家名称")
    position = models.IntegerField(choices=((1, "楚园食堂"), (2, "汉园食堂")), verbose_name="位置")
    floor = models.IntegerField(choices=((1, "一楼"), (2, "二楼")), verbose_name="楼层")
    type = models.IntegerField(choices=((1, "餐品"), (2, "饮品")), verbose_name="商家类型")
    date_apply = models.DateTimeField(auto_now_add=True, verbose_name="申请时间")

    is_passed = models.BooleanField(default=False, verbose_name="是否通过")

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.is_passed:
            self.user.is_active = True
            self.user.save()
            try:
                Business.objects.create(user=self.user, name=self.name, position=self.position,
                                        floor=self.floor,
                                        type=self.type)
            except:
                pass
        super(Authapply, self).save()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "商家认证申请"
        verbose_name_plural = verbose_name


class BusinessTextComment(models.Model):
    business = models.ForeignKey(Business, verbose_name="商家")
    comment = models.CharField(max_length=150, blank=True, verbose_name="评价")
    date_comment = models.DateTimeField(auto_now_add=True, verbose_name="评论时间")

    is_pass = models.BooleanField(default=False, verbose_name="评论是否审核通过")

    def __str__(self):
        return self.comment

    class Meta:
        verbose_name = "商家评论"
        verbose_name_plural = verbose_name

apps/operation/views.py
from django.http import JsonResponse, HttpResponseNotFound
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.shortcuts import render

from business.models import Business, Food, BusinessTextComment
from .models import Order, UserCollect


@login_required(login_url='/')
def makeorder(request):
    try:
        request.session['order'] = request.session['order']
    except:
        request.session['order'] = {}
    foodpk = request.POST.get('foodpk', False)
    businesspk = request.POST.get('businesspk', False)
    num = request.POST.get('num', False)

    def check_attr():
        try:
            f = int(foodpk)
            b = int(businesspk)
            n = int(num)
        except:
            return False

        if f in Food.objects.values_list('pk', flat=True) and b in Business.objects.values_list('pk',
                                                                                                flat=True) and n == 1:
            return True
        else:
            return False
    request.session['order'].update({'business': businesspk, foodpk: num})
    if request.session['order'].__len__() > 2:
        del request.session['order']
        return JsonResponse({'status': -1})

    s = check_attr()
    if s:
        return JsonResponse({'status': 1})
    else:
        return JsonResponse({'status': 0})


@login_required(login_url='/')
def removeorder(request):
    try:
        request.session['order'] = request.session['order']
    except:
        request.session['order'] = {}
    foodpk = request.POST.get('foodpk', False)
    businesspk = request.POST.get('businesspk', False)

    def check_attr():
        try:
            b = int(businesspk)
            f = int(foodpk)
        except:
            return False

        if f in Food.objects.values_list('pk', flat=True) and b in Business.objects.values_list('pk', flat=True):
            return True
        else:
            return False

    del request.session['order'][foodpk]
    s = check_attr()
    if s:
        return JsonResponse({'status': 1})
    else:
        return JsonResponse({'status': 0})


class ShowOrderView(LoginRequiredMixin, TemplateView):
    raise_exception = True

    template_name = 'operation/order.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        try:
            orderdic = request.session['order']
        except:
            return HttpResponseNotFound("您还未点餐")
        food_list = []
        psum = 0
        for fpk in orderdic.keys():
            if fpk == 'business':
                bpk = orderdic['business']
            else:
                try:
                    f = Food.objects.get(pk=fpk)
                    food_list.append(f)
                    psum = psum + f.price
                except:
                    return HttpResponseNotFound()
        context['food_list'] = food_list
        context['pricesum'] = psum
        context['businesspk'] = bpk
        return self.render_to_response(context)

    def post(self, request):
        if not request.user.usertype:
            return JsonResponse({'status': 2})
        if not request.user.can_order:
            return JsonResponse({'status': -1})
        if request.user.get_no_done_order_list():
            return JsonResponse({'status': -2})
        confirm = request.POST.get('confirm', False)
        time = request.POST.get('time', False)
        remarkstr = request.POST.get('remarkstr', '')
        if confirm:
            try:
                orderdic = request.session['order']
            except:
                return HttpResponseNotFound("您还未点餐")
            try:
                for fpk in orderdic.keys():
                    if fpk == 'business':
                        b = Business.objects.get(pk=orderdic['business'])
                        if not b.is_open:
                            return JsonResponse({'status': 0})
                    else:
                        f = Food.objects.get(pk=fpk)
                        Order.objects.create(user=request.user, food=f, date_pickup=time, remark=remarkstr)
            except Exception as e:
                print(e)
                return JsonResponse({'status': 0})
            return JsonResponse({'status': 1})
        else:
            return JsonResponse({'status': 0})


class MycollectView(LoginRequiredMixin, TemplateView):
    raise_exception = True
    template_name = 'operation/collect.html'

    def post(self, request):
        bpk = request.POST.get('bpk', False)
        try:
            b = Business.objects.get(pk=bpk)
        except:
            return JsonResponse({'status': 0})
        try:
            obj, is_created = UserCollect.objects.get_or_create(user=request.user)
            if b in obj.business.all():
                obj.business.remove(b)
                return JsonResponse({'status': 2})
            else:
                obj.business.add(b)
                return JsonResponse({'status': 1})
        except:
            return JsonResponse({'status': 0})


@login_required(login_url='/')
def comment(request, opk):

    try:
        order = request.user.myorder.get(pk=opk)
        business = order.food.business
    except:
        return HttpResponseNotFound()

    if not order.is_done:
        return HttpResponseNotFound()

    if request.method == 'GET':
        return render(request, 'operation/comment.html', {
            'order': order
        })
    elif request.method == 'POST':
        trank = int(request.POST.get('trank', False))
        prank = int(request.POST.get('prank', False))
        textcomment = request.POST.get('textcomment', False)
        try:
            order.trank, order.prank = trank, prank
            average = (trank + prank) / 2
            order.is_comment = True
            order.save()
            if textcomment:
                BusinessTextComment.objects.create(business=order.food.business, comment=textcomment)
            num_order = Order.objects.filter(is_comment=True).count()
            business.total_rank = business.total_rank + average
            business.rank = round(business.total_rank / num_order)
            business.save()
            return JsonResponse({'status': 1})
        except Exception as e:
            print(e)
            return JsonResponse({'status': 0})

templates/operation/collect.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=600px">
    <meta name="format-detection" content="telephone=no">
    <title>智慧食堂</title>
    <link href="https://cdn.bootcss.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/index/style.css' %}">
    <link href="{% static 'css/index/main.css' %}" rel="stylesheet" type="text/css">
    <style>
        .header {
            text-align: center;
            height: 5vh;
            line-height: 5vh;
        }

        .bimg {
            height: 122px;
        }
    </style>
</head>

<body>
<div class="container">
    <h2 class="header"><span class="pull-left"><i class="glyphicon glyphicon-chevron-left" style="cursor: pointer" onclick="window.location.href='{% url 'ucenterindex' %}'"></i> </span>我的收藏</h2>
    <hr size=3px width=100% color=black>
    {% for business in user.get_collect_list %}
        <a href="{% url 'businessdetail' business.pk %}">
            <div class="show row ">
                <div class="col-xs-3">
                    <img src="/media/{{ business.image }}" alt="" class="bimg">
                </div>
                <div class="col-xs-9">
                    <h4 style="margin-left: 10px">{{ business.name }}<em style="float:right; font-style:normal; margin-right: 10px">综合评分：{{ business.rank }}</em>
                    </h4>
                    <span>
        <p style="margin-left: 10px">特色菜：{% for food in business.special.foods.all %}
            {{ food.name }}
        {% empty %}
            {% for food in business.foodlist.all|slice:"3" %}
                {{ food.name }}
            {% endfor %}
        {% endfor %}</p><br>
                    <span><p class="pull-left" style="margin-left: 10px">位置：{{ business.get_position_display }} {{ business.get_floor_display }}</p></span>
        <span><p class="text-right" style="color: #717171; margin-right: 10px">人均消费：{{ business.average }}元</p></span>
</span>
                </div>
            </div>
        </a>
        <hr>
        </div>
    {% endfor %}
</body>

templates/operation/comment.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta id="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1, minimum-scale=1,  user-scalable=no,minimal-ui"
          name="viewport">
    <meta name="format-detection" content="telephone=no">
    <title>评价</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css">
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
    <link href="{% static 'css/operation/iconfont.css' %}" type="text/css" rel="stylesheet">
    <style>
        .icon {
            font-size: 2em;
            color: #bebebe;
            cursor: pointer;
        }

        .active {
            color: rgb(238,173,14)
        }
    </style>
</head>
<body>
<i class="glyphicon glyphicon-chevron-left" style="position: absolute; font-size: 20px; margin: 10px 0 0 10px" onclick="window.location.href='{% url 'ucenterindex' %}'"></i>
<div class="head">
    <span>{{ order.food.business }}</span>
</div>
<div class="food">
    <span>商品名称：{{ order.food.name }}</span>
</div>
<div class="star-body">
    <div class="star-kw">
        <span class="mei">口味</span>
        <i id="k1" class="icon iconfont icon-xing"></i>
        <i id="k2" class="icon iconfont icon-xing"></i>
        <i id="k3" class="icon iconfont icon-xing"></i>
        <i id="k4" class="icon iconfont icon-xing"></i>
        <i id="k5" class="icon iconfont icon-xing"></i>
    </div>
    <div class="star-jg">
        <span class="mei">价格</span>
        <i id="j1" class="icon iconfont icon-xing"></i>
        <i id="j2" class="icon iconfont icon-xing"></i>
        <i id="j3" class="icon iconfont icon-xing"></i>
        <i id="j4" class="icon iconfont icon-xing"></i>
        <i id="j5" class="icon iconfont icon-xing"></i>
    </div>
    <div class="book">
        <input type="text" placeholder="说出您的心声，我们来反馈!" id="textcomment">
    </div>
    <div class="buttont">
        <button type="button" onclick="submitcomment()" name="textcomment"><span>提交评价</span></button>
    </div>
    <div class="ts">
        <span>温馨提示：您的评论我们系统将以匿名方式进行!</span>
    </div>
</div>
<script>
    const klist = [
        '#k1',
        '#k2',
        '#k3',
        '#k4',
        '#k5'
    ];
    const jlist = [
        '#j1',
        '#j2',
        '#j3',
        '#j4',
        '#j5'
    ];
    klist.forEach(e => $(e).click(function (e) {
        for (let i = 0; i < 5; i++) {
            $(klist[i]).removeClass('active');
        }
        for (let i = 0; i < $(this).index(); i++) {
            $(klist[i]).addClass('active');
        }
    }));

    jlist.forEach(e => $(e).click(function (e) {
        for (let i = 0; i < 5; i++) {
            $(jlist[i]).removeClass('active');
        }
        for (let i = 0; i < $(this).index(); i++) {
            $(jlist[i]).addClass('active');
        }
    }));

    function getrank() {
        let ksum = 0;
        let jsum = 0;
        for (let i = 0; i < 5; i++) {
            if ($(klist[i]).hasClass('active')) {
                ksum += 1;
            }
        }
        for (let i = 0; i < 5; i++) {
            if ($(jlist[i]).hasClass('active')) {
                jsum += 1;
            }
        }
        return {
            ksum: ksum,
            jsum: jsum
        }
    }

    function submitcomment() {
        rank = getrank();
        $.post('{% url 'comment' order.pk %}', {
                trank: rank.ksum,
                prank: rank.jsum,
                textcomment: $('#textcomment').val(),
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            function (data) {
                if (data['status']) {
                    alert("提交评价成功");
                    window.location.href = '{% url 'ucenterindex' %}'
                }
                else {
                    alert("出错啦");
                }
            },
            "json")
    }

</script>
</body>
</html>

templates/operation/order.html
{% load staticfiles %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=600px">
    <link rel="shortcut icon" href="#" type="image/x-icon"/>

    <meta name="format-detection" content="telephone=no">
    <title>智慧食堂</title>
    <!--css-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/index/common_css.css' %}">
    <link rel="stylesheet" href="{% static 'css/operation/buy.css' %}">

    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.js"></script>

    <script src="https://cdn.bootcss.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

</head>

<body>
<div id="block">
    <header>
        <div class="row">
            <div class="col-xs-3">
                <a class="glyphicon glyphicon-menu-left" href="{% url 'businessdetail' businesspk %}"></a>
            </div>
            <div class="col-xs-6 text-center">
                <span>预约详情</span>
            </div>
        </div>
    </header>

    <main>
        <div class="row">
            <p>您预约的商品：</p>
            <div class="col-xs-6"><p>菜品名称</p></div>
            <div class="col-xs-3"><p>份数</p></div>
            <div class="col-xs-3"><p>金额</p></div>
        </div>
        <div id="buy">
            {% for food in food_list %}
                <div class="row">
                    <div class="col-xs-6"><p>{{ food.name }}</p></div>
                    <div class="col-xs-3"><p>1份</p></div>
                    <div class="col-xs-3"><p>{{ food.price }}元</p></div>
                </div>
            {% endfor %}
        </div>
        <hr>
        <div class="row">
            <div class="col-xs-6"><p>总计</p></div>
            <div class="col-xs-3"></div>
            <div class="col-xs-3"><p>{{ pricesum }}元</p></div>
        </div>
        <div class="row">
            <div class="col-xs-4"><span style="font-size: 1.7em">取餐时间</span></div>
            <div class="col-xs-4">
                <p>
                    <select class="form-control" id="h">
                        <option value="-1">请选择小时</option>
                        <option value="7">7点</option>
                        <option value="8">8点</option>
                        <option value="9">9点</option>
                        <option value="10">10点</option>
                        <option value="11">11点</option>
                        <option value="12">12点</option>
                        <option value="13">13点</option>
                        <option value="14">14点</option>
                        <option value="15">15点</option>
                        <option value="16">16点</option>
                        <option value="17">17点</option>
                        <option value="18">18点</option>
                        <option value="19">19点</option>
                        <option value="20">20点</option>
                    </select>
                </p>
            </div>
            <div class="col-xs-4">
                <p>
                    <select class="form-control" id="m">
                        <option value="-1">请选择分钟</option>
                        <option value="0">0</option>
                        <option value="10">10</option>
                        <option value="20">20</option>
                        <option value="30">30</option>
                        <option value="40">40</option>
                        <option value="50">50</option>
                    </select>
                </p>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-4">
                <span style="font-size: 1.7em">备注</span>
            </div>
            <div class="col-xs-4">
                <p>
                    <select class="form-control" id="remark1">
                        <option value="-1">请选择口味。不选为食物默认口味</option>
                        <option value="1">不要辣</option>
                        <option value="2">微辣</option>
                        <option value="3">辣</option>
                        <option value="4">特辣</option>
                    </select>
                </p>
            </div>
            <div class="col-xs-4">
                <p>
                <form>
                    <input type="text" class="form-control" placeholder="如有其它要求请输入" id="remark2">
                </form>
                </p>
            </div>
        </div>
    </main>

    <div style="margin-top: 100px">
        <p class="text-center" style="font-size: 2em; color: #d61e06">温馨提示</p>
        <p class="know">1.提交预约之后，在商家接单之前您可以取消此次订单</p>
        <p class="know">2.为保障用商家和用户的权益，商家接单后请您在取餐时间段内到相应窗口取餐</p>
        <p class="know">3.若您晚于取餐时间10分钟以上还未取餐，我们会对用户进行使用限制</p>
    </div>


    <div class="text-center" style="bottom: 0; position: absolute; width: 100%">
        <button type="button" class="btn btn-success btn-lg btn-block" onclick="submit()">提交订单</button>
    </div>
</div>

<script>
    function submit() {
        if ($('#h').val() == -1 || $('#m').val() == -1) {
            alert('您还未选择取餐时间');
            return false;
        }
        time = $('#h').val() + ':' + $('#m').val();
        if ($('#remark1').val() === -1) {
            remarkstr = '默认口味' + $('#remark2').val();
        } else {
            remarkstr = $('#remark1').find("option:selected").text() + $('#remark2').val();
        }
        $.post("{% url 'showorder' %}", {confirm: 1, csrfmiddlewaretoken: '{{ csrf_token }}', time: time, remarkstr: remarkstr},
            function (data) {
                if (data['status'] === 1) {
                    alert("您的订单已成功提交，请待商家接受预约后前往个人中心查看相应订单信息");
                    window.location.href = "/";
                }
                else if (data['status'] === 0) {
                    alert("提交预约失败，该商家可能目前未开启预约");
                    window.location.href = "/";
                }
                else if (data['status'] === 2) {
                    alert("商家并不能预约餐饮");
                    window.location.href = "/";
                } else if (data['status'] === -1) {
                    alert("由于您之前发生过预约未取餐的行为，后台已自动限制您使用，请到关于我们联系开发人员解除限制");
                    window.location.href = "/";
                } else if (data['status'] === -2) {
                    alert("您目前还有未完成的进行中订单，请处理后再预约");
                    window.location.href = "/";
                }
            }
            , "json");
    }
</script>
</body>
</html>